version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - "localhost:127.0.0.1"

  pgsql:
    image: postgres:12.2-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=points
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
